--------------------------------------------------------
--  File created - Thursday-March-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EBA_DEMO_TF_EMP2
--------------------------------------------------------

  CREATE TABLE "EBA_DEMO_TF_EMP2" 
   (	"EMPNO" NUMBER, 
	"ENAME" VARCHAR2(50), 
	"JOB" VARCHAR2(50), 
	"MGR" NUMBER, 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER, 
	"COMM_ELIG" CHAR(1), 
	"RAISE_ELIG" CHAR(1), 
	"RIFF_ELIG" CHAR(1)
   ) ;
REM INSERTING into EBA_DEMO_TF_EMP2
SET DEFINE OFF;
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7839,'ALLEN','SALESMAN',7698,to_date('17-NOV-81 12:00.00','DD-MON-RR HH:MI.SS'),5000,null,30,'Y','Y','N');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7698,'BLAKE','MANAGER',7839,to_date('01-MAY-81 12:00.00','DD-MON-RR HH:MI.SS'),2850,null,30,'N','Y','N');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7782,'CLARK-SMITH','MANAGER',7839,to_date('09-JUN-81 12:00.00','DD-MON-RR HH:MI.SS'),2450,null,10,'N','Y','N');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7566,'JONES','MANAGER',7839,to_date('02-APR-81 12:00.00','DD-MON-RR HH:MI.SS'),2975,null,20,'N','Y','N');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7788,'SCOTTIE','ANALYST',7566,to_date('09-DEC-82 12:00.00','DD-MON-RR HH:MI.SS'),30000,null,20,'Y','Y','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7902,'TURNER','SALESMAN',7566,to_date('03-DEC-81 12:00.00','DD-MON-RR HH:MI.SS'),3000,null,30,'N','Y','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7499,'SMITH-CLARK','CLERK',7698,to_date('20-FEB-81 12:00.00','DD-MON-RR HH:MI.SS'),1600,300,30,'Y','Y',null);
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7521,'WARD','SALESMAN',7698,to_date('22-FEB-81 12:00.00','DD-MON-RR HH:MI.SS'),1250,500,30,'Y','Y',null);
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7654,'KING','PRESIDENT',null,to_date('28-SEP-81 12:00.00','DD-MON-RR HH:MI.SS'),1250,1400,40,'Y','N','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7844,'TURNER','SALESMAN',7698,to_date('08-SEP-81 12:00.00','DD-MON-RR HH:MI.SS'),1500,0,30,'Y','Y',null);
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7876,'ADAMS','CLERK',7788,to_date('12-JAN-83 12:00.00','DD-MON-RR HH:MI.SS'),1100,null,20,'N','Y','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7900,'JAMESON','SALESMAN',7698,to_date('03-DEC-81 12:00.00','DD-MON-RR HH:MI.SS'),950,null,30,'Y','Y','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7934,'MILLER','CLERK',7782,to_date('23-JAN-82 12:00.00','DD-MON-RR HH:MI.SS'),1300,100,10,'Y','N','N');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7902,'TURNER','SALESMAN',7566,to_date('03-DEC-81 12:00.00','DD-MON-RR HH:MI.SS'),3000,null,30,'N','Y','Y');
Insert into EBA_DEMO_TF_EMP2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,COMM_ELIG,RAISE_ELIG,RIFF_ELIG) values (7902,'TURNER','SALESMAN',7566,to_date('03-DEC-81 12:00.00','DD-MON-RR HH:MI.SS'),3000,null,30,'N','Y','Y');
--------------------------------------------------------
--  Constraints for Table EBA_DEMO_TF_EMP2
--------------------------------------------------------

  ALTER TABLE "EBA_DEMO_TF_EMP2" MODIFY ("EMPNO" NOT NULL ENABLE);
